---
name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Linter
        run: |
          flake8 --max-line-length=100 --ignore E501
      - name: Build package
        run: |
          python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: cloudproof_py_dist
          path: ./dist
          retention-days: 1

  test:
    services:
      kms:
        image: ghcr.io/cosmian/kms:4.5.0
        ports:
          - 9998:9998
      findex_cloud:
        image: ghcr.io/cosmian/findex_cloud:0.1.0
        ports:
          - 8080:8080
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: cloudproof_py_dist
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-termcolor>=1.1 types_redis>=4.3 requests>=2.28 types-requests>=2.28
          scripts/ci_install_pyo3_builds.sh
          pip install cloudproof_py*.whl
      - name: Type-check
        run: |
          mypy src/cloudproof_py/anonymization/
          mypy src/cloudproof_py/cover_crypt/
          mypy src/cloudproof_py/findex/
          mypy src/cloudproof_py/fpe/
          mypy tests/
          mypy examples/cli_demo
          mypy examples/findex_upsert_search
          mypy examples/cover_crypt
      - name: Run tests
        run: |
          python tests/non_regression_cover_crypt.py --test --write
          python tests/findex_cloud.py
          python -m unittest tests/test*.py
      - name: Upload non-regression test vectors
        uses: actions/upload-artifact@v3
        with:
          name: cloudproof_python
          path: |
            ./tests/data/export/non_regression_vector.json
            ./tests/data/export/sqlite.db
          retention-days: 1
          if-no-files-found: error

  cloudproof_java:
    needs: test
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof_java_in_docker.yml@develop
    with:
      branch: develop
      target: x86_64-unknown-linux-gnu
      extension: so
      destination: linux-x86-64
      os: ubuntu-20.04
      kms-version: feat-edit_policy
      findex-cloud-version: 0.1.0
      copy_fresh_build: false
      copy_regression_files: |
        cp ./cloudproof_python/non_regression_vector.json src/test/resources/cover_crypt/non_regression/python_non_regression_vector.json
        cp ./cloudproof_python/sqlite.db                  src/test/resources/findex/non_regression/python_sqlite.db

  cloudproof_js:
    needs: test
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof_js.yml@develop
    with:
      branch: develop
      target: wasm32-unknown-unknown
      kms-version: feat-edit_policy
      findex-cloud-version: 0.1.0
      copy_fresh_build: false
      copy_regression_files: |
        cp ./cloudproof_python/non_regression_vector.json tests/data/cover_crypt/non_regression/python_non_regression_vector.json
        cp ./cloudproof_python/sqlite.db                  tests/data/findex/non_regression/python_sqlite.db

  cloudproof_flutter:
    needs:
      - test
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof_flutter.yml@develop
    with:
      branch: develop
      target: x86_64-unknown-linux-gnu
      extension: so
      copy_fresh_build: false
      copy_regression_files: |
        cp ./cloudproof_python/non_regression_vector.json test/resources/cover_crypt/non_regression/python_non_regression_vector.json
        cp ./cloudproof_python/sqlite.db                  test/resources/findex/non_regression/python_sqlite.db

  cleanup:
    needs:
      - cloudproof_flutter
      - cloudproof_java
      - cloudproof_js
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit
