---
name: Build and test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Linter
        run: |
          flake8 --max-line-length=100 --ignore E501

  cloudproof_python:
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof_python.yml@develop
    with:
      branch: ${{ github.head_ref }}
      target: x86_64-unknown-linux-gnu
      kms-version: 4.10.0
      findex-cloud-version: 0.3.1
      copy_fresh_build: false
      regression_files: |
        ./tests/data/export/non_regression_vector.json
        ./tests/data/export/sqlite.db

  cloudproof_java:
    needs: cloudproof_python
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof_java_in_docker.yml@develop
    with:
      branch: develop
      target: x86_64-unknown-linux-gnu
      extension: so
      destination: linux-x86-64
      os: ubuntu-20.04
      kms-version: 4.10.0
      findex-cloud-version: 0.3.1
      copy_fresh_build: false
      copy_regression_files: |
        cp ./cloudproof_python/non_regression_vector.json src/test/resources/cover_crypt/non_regression/python_non_regression_vector.json
        cp ./cloudproof_python/sqlite.db                  src/test/resources/findex/non_regression/python_sqlite.db

  cloudproof_js:
    needs: cloudproof_python
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof_js.yml@develop
    with:
      branch: develop
      target: wasm32-unknown-unknown
      kms-version: 4.10.0
      findex-cloud-version: 0.3.1
      copy_fresh_build: false
      copy_regression_files: |
        cp ./cloudproof_python/non_regression_vector.json tests/data/cover_crypt/non_regression/python_non_regression_vector.json
        cp ./cloudproof_python/sqlite.db                  tests/data/findex/non_regression/python_sqlite.db

  cloudproof_flutter:
    needs:
      - cloudproof_python
    uses: Cosmian/reusable_workflows/.github/workflows/cloudproof_flutter.yml@develop
    with:
      branch: develop
      target: x86_64-unknown-linux-gnu
      extension: so
      copy_fresh_build: false
      copy_regression_files: |
        cp ./cloudproof_python/non_regression_vector.json test/resources/cover_crypt/non_regression/python_non_regression_vector.json
        cp ./cloudproof_python/sqlite.db                  test/resources/findex/non_regression/python_sqlite.db

  cleanup:
    needs:
      - lint
      - cloudproof_flutter
      - cloudproof_java
      - cloudproof_js
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit
