---
name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Linter
        run: |
          flake8 --max-line-length=100
      - name: Build package
        run: |
          python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: cloudproof_py_dist
          path: ./dist
          retention-days: 1

  test:
    services:
      kms:
        image: cosmian/kms:latest
        env:
          COSMIAN_SERVER_URL: http://localhost:9998
          KMS_PUBLIC_PATH: /tmp
          KMS_PRIVATE_PATH: /tmp
          KMS_SHARED_PATH: /tmp
        ports:
          - 9998:9998
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: cloudproof_py_dist
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy types-termcolor>=1.1 types_redis>=4.3
          scripts/ci_install_pyo3_builds.sh
          pip install cloudproof_py*.whl
      - name: Type-check
        run: |
          mypy src/cloudproof_py/findex/ src/cloudproof_py/cover_crypt/
          mypy tests/
          mypy examples/cli_demo
          mypy examples/findex_upsert_search
          mypy examples/cover_crypt
      - name: Run tests
        run: |
          python -m unittest tests/test*.py
